//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CafeRestorantOtomasyonu
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cafes
    {
        public int CafeID { get; set; }
        public int TableCount { get; set; }
        public string CafeEntry { get; set; }
        public string CafeLoginKey { get; set; }
    }
}
