//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CafeRestorantOtomasyonu
{
    using System;
    using System.Collections.Generic;
    
    public partial class Personals
    {
        public string PersonelID { get; set; }
        public string PersonalName { get; set; }
        public string PersonalSurname { get; set; }
        public string PersonalCell { get; set; }
        public string PersonalRank { get; set; }
    }
}
